# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClassConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.PositiveIntegerField(auto_created=True, max_length=100, verbose_name='渠道ID')),
                ('name', models.CharField(max_length=200, verbose_name='渠道名称')),
                ('channel_type', models.CharField(choices=[('ONLINE', '线上'), ('OFFLINE', '线下')], max_length=20, verbose_name='渠道类型')),
                ('operation_channel_type', models.CharField(choices=[('ZJJ', '转介绍'), ('LDSD', '流动收单'), ('DDSD', '定点收单'), ('ZXSCHD', '中心市场活动'), ('YYHZHD', '异业合作活动'), ('SQGYHD', '社区公益活动')], max_length=20, verbose_name='运营渠道')),
                ('fee', models.PositiveIntegerField(default=0, max_length=20, verbose_name='费用')),
                ('isActive', models.BooleanField(default=bool, max_length=10, verbose_name='启用')),
                ('place', models.CharField(max_length=200, verbose_name='地点')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Center', verbose_name='中心')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(auto_created=True, blank=True, max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('trace_status', models.CharField(blank=True, max_length=100, null=True)),
                ('trace_count', models.PositiveIntegerField(blank=True, max_length=100, null=True)),
                ('promised_arrive_time', models.DateField(blank=True, max_length=100, null=True)),
                ('birth', models.DateField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(blank=True, max_length=100, null=True)),
                ('school', models.DateField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
