# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ZJJ', '转介绍'), ('LDSD', '流动收单'), ('DDSD', '定点收单'), ('ZXSCHD', '中心市场活动'), ('YYHZHD', '异业合作活动'), ('SQGYHD', '社区公益活动')], max_length=20, verbose_name='运营渠道')),
            ],
        ),
        migrations.AlterField(
            model_name='marketchannel',
            name='channel_id',
            field=models.PositiveIntegerField(auto_created=True, verbose_name='渠道ID'),
        ),
        migrations.AlterField(
            model_name='marketchannel',
            name='fee',
            field=models.PositiveIntegerField(default=0, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='marketchannel',
            name='isActive',
            field=models.BooleanField(default=bool, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='marketchannel',
            name='operation_channel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.OperationChannel', verbose_name='运营渠道'),
        ),
    ]
