# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20170903_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='center_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classconsultant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationchannel',
            name='name',
            field=models.CharField(choices=[('转介绍', '转介绍'), ('流动收单', '流动收单'), ('定点收单', '定点收单'), ('中心市场活动', '中心市场活动'), ('异业合作活动', '异业合作活动'), ('社区公益活动', '社区公益活动')], max_length=20, verbose_name='运营渠道'),
        ),
    ]
