# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20170903_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketchannel',
            name='channel_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, verbose_name='渠道ID'),
        ),
    ]
