# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20170903_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketchannel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
