# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_marketchannel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketchannel',
            name='channel_type',
            field=models.CharField(choices=[('ONLINE', '线上'), ('OFFLINE', '线下')], default='ONLINE', max_length=20, verbose_name='渠道类型'),
        ),
    ]
