# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_auto_20170903_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': '中心管理'},
        ),
        migrations.AlterModelOptions(
            name='marketchannel',
            options={'verbose_name': '市场渠道管理'},
        ),
        migrations.AlterModelOptions(
            name='operationchannel',
            options={'verbose_name': '运营渠道管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生'},
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=20, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='家庭电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='家长姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promised_arrive_time',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='诺到时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='就读学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trace_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='跟踪次数'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trace_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='跟踪状态'),
        ),
    ]
