# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20170903_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassConsultant',
            new_name='CourseConsultant',
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': '中心管理', 'verbose_name_plural': '中心管理'},
        ),
        migrations.AlterModelOptions(
            name='marketchannel',
            options={'verbose_name': '市场渠道管理', 'verbose_name_plural': '市场渠道管理'},
        ),
        migrations.AlterModelOptions(
            name='operationchannel',
            options={'verbose_name': '运营渠道管理', 'verbose_name_plural': '运营渠道管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生管理', 'verbose_name_plural': '学生管理'},
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='student',
            name='refer_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='推荐人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='登记日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学员姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(auto_created=True, blank=True, max_length=100, null=True, verbose_name='学员工编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='trace_count',
            field=models.PositiveIntegerField(default=0, verbose_name='跟踪次数'),
        ),
    ]
