# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapp', '0011_auto_20170903_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '教室管理',
                'verbose_name_plural': '教室管理',
            },
        ),
        migrations.CreateModel(
            name='ClassRoomTimeSlotManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(max_length=100)),
                ('endTime', models.TimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractManagement',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('tuition', models.FloatField(verbose_name='学费')),
                ('contract_status', models.CharField(choices=[('NOT PAID', '未付款'), ('PAID', '已付款')], max_length=200, verbose_name='合同状态')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_resign', models.BooleanField(default=False, verbose_name='续约')),
            ],
            options={
                'verbose_name': '合同管理',
                'verbose_name_plural': '合同管理',
            },
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('level', models.IntegerField(verbose_name='课程级别')),
                ('tuition', models.FloatField(verbose_name='学费')),
                ('discount_fee', models.FloatField(verbose_name='减免金额')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartNewClassPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='开班计划ID')),
                ('start_date', models.DateField(max_length=100, verbose_name='开班日期')),
                ('end_date', models.DateField(max_length=100, verbose_name='结束日期')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('course_duration', models.FloatField(verbose_name='总课时')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Center')),
                ('chinese_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_teacher', to='schoolapp.Staff', verbose_name='中教老师')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.ClassRoom', verbose_name='上课教室')),
                ('english_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_teacher', to='schoolapp.Staff', verbose_name='外教老师')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='schoolapp.Staff', verbose_name='班主任')),
            ],
            options={
                'verbose_name': '开班计划',
                'verbose_name_plural': '开班计划',
            },
        ),
        migrations.AlterModelOptions(
            name='courseconsultant',
            options={'verbose_name': '课程顾问', 'verbose_name_plural': '课程顾问'},
        ),
        migrations.AddField(
            model_name='student',
            name='contact_source',
            field=models.CharField(blank=True, choices=[('tmk-out', 'tmk-out'), ('tmk-in', 'tmk-in'), ('walk-in', 'walk-in')], max_length=100, null=True, verbose_name='方式'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证件号'),
        ),
        migrations.AddField(
            model_name='student',
            name='refer_date',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='登记日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(auto_created=True, blank=True, max_length=100, null=True, verbose_name='学员编号'),
        ),
        migrations.AddField(
            model_name='contractmanagement',
            name='course_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.CoursePlan', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='contractmanagement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='classroomtimeslotmanagement',
            name='time_slots',
            field=models.ManyToManyField(to='schoolapp.ClassTimeSlot'),
        ),
    ]
